# Generated by Django 4.2.4 on 2023-08-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_models', '0003_customer_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='cus_id',
            new_name='customers',
        ),
    ]
