# Generated by Django 4.2.4 on 2023-08-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_models', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.TextField(max_length=100)),
                ('cus_email', models.EmailField(max_length=254)),
                ('cus_mobile', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.TextField()),
                ('cus_qty', models.TextField(max_length=100)),
                ('cus_id', models.ManyToManyField(to='my_models.customer')),
            ],
        ),
    ]
