# Generated by Django 4.2.4 on 2023-08-09 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_models', '0004_rename_cus_id_products_customers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
